name: linting, testing, building

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Build production project
              run: npm run build:prod
              if: always()

            - name: Lint TypeScript
              run: npm run lint:ts
              if: always()

            - name: Lint CSS/SCSS
              run: npm run lint:scss
              if: always()

            - name: Run unit tests
              run: npm run unit
              if: always()

            # - name: Build Storybook
            #   run: npm run build-storybook
